### ISSUE TITLE
fix database updater/harvesting fail

### ISSUE THREAD

**Issue by mentaer** [CEDEUS/plataforma-datos-django#2]
@csfuente thanks!

**Comment by csfuente** [comment]
Ya se encuentra actualizando nuevamente todos los días desde las 4 AM.
El sistema actualizador se encontraba bien pero no tenía un control sobre los requests que no podía alcanzar su destino. Se creó sistema de colas de petición con las URL con problemas para que vuelva a intentar cada 30 minutos después.
